[project]
name = "api-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "union>=0.1.182",
    "uvicorn>=0.34.2",
]
